spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: share
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/changelog.yaml
  web:
    resources:
      add-mappings: false
minio:
  bucket: share
logbook:
  format:
    style: json
  predicate:
    exclude:
      - path: /actuator/**
logging:
  level:
    org.zalando.logbook: TRACE
#server:
#  port: 8080