spring:
  application:
    name: share
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/changelog.yaml
minio:
  bucket: share
logbook:
  format:
    style: json
  predicate:
    exclude:
      - path: /actuator/**
logging:
  level:
    org.zalando.logbook: TRACE