apiVersion: apps/v1
kind: Deployment
metadata:
  name: share-backend
  labels:
    app: share-backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: share-backend-app
  template:
    metadata:
      name: share-backend-app
      labels:
        app: share-backend-app
    spec:
      containers:
        - name: share-backend
          image: share-backend-image
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: share-backend-secret
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: spring-application-config
              mountPath: /app/config
      volumes:
        - name: spring-application-config
          configMap:
            name: backend-application-config
      restartPolicy: Always
      