apiVersion: v1
kind: Service
metadata:
  name: share-backend
spec:
  selector:
    app: share-backend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
    - protocol: TCP
      port: 81
      targetPort: 8081
  type: NodePort
  