package ru.taynov.share.utils

const val INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
const val METHOD_ARGUMENT_NOT_VALID_ERROR = "METHOD_ARGUMENT_NOT_VALID_ERROR"
const val VALIDATION_ERROR = "VALIDATION_ERROR"
const val INVALID_PARAMETERS = "INVALID_PARAMETERS"
const val MAX_FILE_SIZE = 104857600L
const val MAX_FILES_NUMBER = 20