apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgres-db
spec:
  teamId: "taynov.ru"
  volume:
    size: 1Gi
    storageClass: local-path
  enableMasterLoadBalancer: true
  numberOfInstances: 2
  users:
    share:
      - superuser
  databases:
    app: share
  postgresql:
    version: "15"